version: 2

project_name: lark

builds:
  - id: lark
    main: ./cmd/lark
    binary: lark
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X lark/internal/version.Version={{ .Tag }}
      - -X lark/internal/version.Commit={{ .ShortCommit }}
      - -X lark/internal/version.Date={{ .Date }}
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
  - id: lark_darwin
    main: ./cmd/lark
    binary: lark
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X lark/internal/version.Version={{ .Tag }}
      - -X lark/internal/version.Commit={{ .ShortCommit }}
      - -X lark/internal/version.Date={{ .Date }}
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - id: lark
    builds:
      - lark
      - lark_darwin
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

brews:
  - name: lark
    # Users will install via: brew install rintays/tap/lark
    repository:
      owner: rintays
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/rintays/lark-cli
    description: A Go CLI for Feishu/Lark inspired by gog
    license: MIT
    install: |
      bin.install "lark"
    test: |
      system "#{bin}/lark", "version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
